change in regression testcase; adding core finder; mail format for core; results upto build 4.1.5.52;add smoke ipv6,referer,reactive replay,NvM testcase

diff --git a/lib/automation_util b/lib/automation_util
--- a/lib/automation_util
+++ b/lib/automation_util
@@ -24,7 +24,7 @@ TS_LOG_DIR="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/$TSR_NUM/logs"
 SAVED_STRING=$(echo $VAR_VALUE_SUM_RESULT | cut -d "," -f5|sed 's/"//g')
 RELEASE_ID=$(cat $NS_WDIR/etc/version |grep VERSION| cut -d " "  -f2| cut -d . -f1,2,3)
 BUILD_ID=$(cat $NS_WDIR/etc/version | tail -1  | cut -d " " -f2)
-
+#ParamListFile="/home/ashmita/workspace/Shell/ParamList"
 
 #Testidx will be passed as second args by ts_run in check status itself
 T_RUN_ID=$2
@@ -217,7 +217,7 @@ log_status_and_exit_ex(){
     #echo "$(get_tname),$(get_testidx),${RELEASE_ID},${BUILD_ID},${COMP},${status_show},${categoryid},${remarks}" >>$R_FILE
     echo "$(get_tname),$(get_testidx),${COMP},${categoryid},${status_show},${remarks}" >>${R_FILE}
     
-    [ "X$status" = "XFAIL" ] && exit -1
+    [ "X$status" = "XFAIL" ] && exit 3
 }
 
 
@@ -281,13 +281,11 @@ project_name(){
 remote_ssh(){
     host="$1"
     cmd="$2"
-
     default_user="root"
     default_passwd="abeona" 
 
     user=${default_user}
     passwd=${default_passwd}
-
     #Safety Checks, If user and password is provided override them
     [ ! -z $3 ] && user="$3"
     [ ! -z $4 ] && passwd="$4"
@@ -295,5 +293,40 @@ remote_ssh(){
     PYTHON_SSH="python /home/regression/bin/ssh.py"
 
     ${PYTHON_SSH} ${host} ${user} ${passwd} "${cmd}"
+}
+
+function baslineTR()
+{
+    tsrId=$1
+    tsrNo=$2
+    testcaseName=$3
+    tName=$(get_tname)
+    baselineTr=$(grep -w "$tName" $NS_WDIR/logs/tsr/$tsrId/$tsrNo/${testcaseName}_results.csv|cut -d ',' -f2)
+    echo $baselineTr
+}
+
+#fetches data from summary_gdf.data file for baseline/current test run
+
+function testStats()
+{    test_run=$1
+    test_log=$2 #either it is baseline(0) or current(1)
+    param_string=$3
+    param_name=$4
+    
+    #fetches data for baseline test run (test_log = 0 represents baseline test run)
+    if [ $test_log -eq 0 ]; then
+        param_value="${param_name}_baseline"
+        param_value=`grep -w "${param_string}" $NS_WDIR/logs/TR$test_run/summary_gdf.data |cut -d '|' -f6`
+        echo ${param_value}
+
+        #fetches data for current test run (test_log = 1 represents current test run)
+    elif [ $test_log -eq 1 ]; then
+        param_value="${param_name}_current"
+        param_value=$(grep -w "$param_string" $NS_WDIR/logs/TR$test_run/summary_gdf.data |cut -d '|' -f6)
+        echo $param_value
+
+    else
+        echo "invalid testLog argument"
+    fi
 }
 
diff --git a/lib/automation_util_latest b/lib/automation_util_latest
--- a/lib/automation_util_latest
+++ b/lib/automation_util_latest
@@ -14,47 +14,48 @@
 # 3. To add new utility modules as per design changes
 #------------------------------------------------------------
 
-WORKBENCH="/home/automation/workbench/automation/nscore"
-D_LOG_FILE="${WORKBENCH}/logs/automation_debug.log"
-E_LOG_FILE="${WORKBENCH}/logs/automation_error.log"
-COMPONENT_ID=$(grep  "CONFIG" /etc/cav.conf  |awk '{print $2}' |cut -d '>' -f1)
-TEST_CYCLE_NUM=$(cat $TEMP_FILE|grep "Test Cycle Number"|cut -d "=" -f2|sed -e 's/^[ \t]*//g')
-TSR_NUM=$(cat $TEMP_FILE|grep "Test Suite Run Number"|cut -d "=" -f2|sed -e 's/^[ \t]*//g')
-TS_LOG_DIR="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/$TSR_NUM/logs"
-SAVED_STRING=$(echo $VAR_VALUE_SUM_RESULT | cut -d "," -f5|sed 's/"//g')
-RELEASE_ID=$(cat $NS_WDIR/etc/version |grep VERSION| cut -d " "  -f2| cut -d . -f1,2,3)
-BUILD_ID=$(cat $NS_WDIR/etc/version | tail -1  | cut -d " " -f2)
-
+#WORKBENCH="/home/automation/workbench/automation/nscore"
+#D_LOG_FILE="${WORKBENCH}/logs/automation_debug.log"
+#E_LOG_FILE="${WORKBENCH}/logs/automation_error.log"
+#COMPONENT_ID=$(grep  "CONFIG" /etc/cav.conf  |awk '{print $2}' |cut -d '>' -f1)
+#TEST_CYCLE_NUM=$(cat $TEMP_FILE|grep "Test Cycle Number"|cut -d "=" -f2|sed -e 's/^[ \t]*//g')
+#TSR_NUM=$(cat $TEMP_FILE|grep "Test Suite Run Number"|cut -d "=" -f2|sed -e 's/^[ \t]*//g')
+#TS_LOG_DIR="$NS_WDIR/logs/tsr/$TEST_CYCLE_NUM/$TSR_NUM/logs"
+TS_LOG_DIR="$NS_WDIR/logs/tsr/160801_195657/4581/logs"
+#SAVED_STRING=$(echo $VAR_VALUE_SUM_RESULT | cut -d "," -f5|sed 's/"//g')
+#RELEASE_ID=$(cat $NS_WDIR/etc/version |grep VERSION| cut -d " "  -f2| cut -d . -f1,2,3)
+#BUILD_ID=$(cat $NS_WDIR/etc/version | tail -1  | cut -d " " -f2)
+ParamListFile="/home/ashmita/workspace/Shell/ParamList"
 
 #Testidx will be passed as second args by ts_run in check status itself
-T_RUN_ID=$2
+#T_RUN_ID=$2
 
 
 # Returns the current partition of the last ran test
-get_test_partition() {
-	 if [ -f $NS_WDIR/logs/TR${T_RUN_ID}/.curPartition ]; then
-         partition=$(head -1 $NS_WDIR/logs/TR${T_RUN_ID}/.curPartition | cut -d '=' -f2)
-         echo $partition
-     else
-         echo ""
-	 fi
-}
+#get_test_partition() {
+#	 if [ -f $NS_WDIR/logs/TR${T_RUN_ID}/.curPartition ]; then
+#         partition=$(head -1 $NS_WDIR/logs/TR${T_RUN_ID}/.curPartition | cut -d '=' -f2)
+#         echo $partition
+#     else
+#         echo ""
+#	 fi
+#}
 
-T_ID_REQ_PATH="$NS_WDIR/logs/TR$T_RUN_ID/$(get_test_partition)/ns_logs/req_rep"
+#T_ID_REQ_PATH="$NS_WDIR/logs/TR$T_RUN_ID/$(get_test_partition)/ns_logs/req_rep"
 
 
 #can be called to get testsuite name
-testsuite_name(){
-    testsuitname=$1
-    echo "$testsuitname"
-}
+#testsuite_name(){
+#    testsuitname=$1
+#    echo "$testsuitname"
+#}
 
 
 #can be called to get recently executed test name
-get_tname(){
-    T_NAME=$(grep -e TNAME $NS_WDIR/logs/TR${T_RUN_ID}/scenario |awk '{print $2}')
-    echo ${T_NAME}
-}
+#get_tname(){
+#    T_NAME=$(grep -e TNAME $NS_WDIR/logs/TR${T_RUN_ID}/scenario |awk '{print $2}')
+#    echo ${T_NAME}
+#}
 
 
 #can be called to get recently executed test run number
@@ -82,17 +83,17 @@ debug_log(){
 
 
 #can be called to get log info
-error_log(){
-    debug_log $* >> ${D_LOG_FILE}
-    echo "$(date +"%F %X") | $*" >> ${E_LOG_FILE}
-}
+#error_log(){
+#    debug_log $* >> ${D_LOG_FILE}
+#    echo "$(date +"%F %X") | $*" >> ${E_LOG_FILE}
+#}
 
 
 #can be called to get log info
-log_msg(){
-    echo -e $*
-    echo -e $* >> ${R_FILE}
-}
+#log_msg(){
+#    echo -e $*
+#    echo -e $* >> ${R_FILE}
+#}
 
 
 #can be called to get status log
@@ -113,83 +114,83 @@ log_status_and_exit(){
 
 #can be called to generate report
 #log_status_and_exit(){
-gen_report(){
-    log_msg "Test Case Name\t\t\t= `get_tname`"
-    log_msg "Test Run Number\t\t\t= $T_RUN_ID"
-    log_msg "Duration\t\t\t= $SD_DURATION"
-    log_msg "TCP Connections Total\t\t= $SD_TotalConn"
-    log_msg "TCP Connections Success\t\t= $SD_TotalSuccConn"
-    log_msg "Total Pass Pct\t\t\t= $SD_TotalPassPct"
-    log_msg "Url Total\t\t\t= $SD_TotalURLHits"
-    log_msg "Url Success\t\t\t= $SD_TotalSuccURL"
-    log_msg "URL Failures\t\t\t= $SD_URLFailures"
-    log_msg "URL Hits/Sec\t\t\t= $SD_URLHitsPerSec"
-    log_msg "TCP Tx Throughput(Kbps)\t\t= $SD_TcpTx"
-    log_msg "TCP Rx Throughput(Kbps)\t\t= $SD_TcpRx"
-    log_msg "Ethernet Tx Throughput(Kbps)\t= $SD_EthTx"
-    log_msg "Ethernet Rx Throughput(Kbps)\t= $SD_EthRx"
-    log_msg "Total page fail(count)\t"= $PAGE_FAIL
-}
+#gen_report(){
+#    log_msg "Test Case Name\t\t\t= `get_tname`"
+#    log_msg "Test Run Number\t\t\t= $T_RUN_ID"
+#    log_msg "Duration\t\t\t= $SD_DURATION"
+#    log_msg "TCP Connections Total\t\t= $SD_TotalConn"
+#    log_msg "TCP Connections Success\t\t= $SD_TotalSuccConn"
+#    log_msg "Total Pass Pct\t\t\t= $SD_TotalPassPct"
+#    log_msg "Url Total\t\t\t= $SD_TotalURLHits"
+#    log_msg "Url Success\t\t\t= $SD_TotalSuccURL"
+#    log_msg "URL Failures\t\t\t= $SD_URLFailures"
+#    log_msg "URL Hits/Sec\t\t\t= $SD_URLHitsPerSec"
+#    log_msg "TCP Tx Throughput(Kbps)\t\t= $SD_TcpTx"
+#    log_msg "TCP Rx Throughput(Kbps)\t\t= $SD_TcpRx"
+#    log_msg "Ethernet Tx Throughput(Kbps)\t= $SD_EthTx"
+#    log_msg "Ethernet Rx Throughput(Kbps)\t= $SD_EthRx"
+#    log_msg "Total page fail(count)\t"= $PAGE_FAIL
+#}
 
 
 #can be called to generate summary report of entire suite in txt file
-set_test_summary_ex(){
-    PASS_COUNT=$(grep -cw "pass" $R_FILE)
-    FAIL_COUNT=$(grep -cw "fail" $R_FILE)
-    TOTAL_CASES=$(cat $R_FILE| grep -v ^Test| wc -l)
-}
+#set_test_summary_ex(){
+#    PASS_COUNT=$(grep -cw "pass" $R_FILE)
+#    FAIL_COUNT=$(grep -cw "fail" $R_FILE)
+#    TOTAL_CASES=$(cat $R_FILE| grep -v ^Test| wc -l)
+#}
 
 
 #can be called to get number of testcases failed
-get_failed_test_count(){
-    FAIL_COUNT=$(grep -ci ",FAIL," $R_FILE)
-    echo $FAIL_COUNT
-}
+#get_failed_test_count(){
+#    FAIL_COUNT=$(grep -ci ",FAIL," $R_FILE)
+#    echo $FAIL_COUNT
+#}
 
 
 #can be called to get number of testcases passed
-get_passed_test_count(){
-    PASS_COUNT=$(grep -ci ",PASS," $R_FILE)
-    echo $PASS_COUNT
-}
+#get_passed_test_count(){
+#    PASS_COUNT=$(grep -ci ",PASS," $R_FILE)
+#    echo $PASS_COUNT
+#}
 
 
 #can be called to get number of total testcases
-get_total_test_count(){
-    TOTAL_COUNT=$(($(get_passed_test_count) + $(get_failed_test_count)))
-    echo $TOTAL_COUNT
-}
+#get_total_test_count(){
+#    TOTAL_COUNT=$(($(get_passed_test_count) + $(get_failed_test_count)))
+#    echo $TOTAL_COUNT
+#}
 
 
 #can be called to set summary report
-set_test_summary(){
-    COUNT=$(grep -cw "PASS" $R_FILE)
-    TOTAL_CASES=$(grep -c "TESTRESULT" $R_FILE)
-    echo -e "SUMMARY\t\t\t\t= $COUNT/$TOTAL_CASES cases passed" >>$R_FILE
-}
+#set_test_summary(){
+#    COUNT=$(grep -cw "PASS" $R_FILE)
+#    TOTAL_CASES=$(grep -c "TESTRESULT" $R_FILE)
+#    echo -e "SUMMARY\t\t\t\t= $COUNT/$TOTAL_CASES cases passed" >>$R_FILE
+#}
 
 
 #can be called to set testsuite header
-set_results_header(){
-    echo "*-----------------------------------------------------*" >>$R_FILE
-    echo "     Test Executed By  : `whoami`" >> $R_FILE
-    echo "     Date/Time         : `date +%D`/`date +%X`" >> $R_FILE
-    echo "*-----------------------------------------------------*" >>$R_FILE
-}
+#set_results_header(){
+#    echo "*-----------------------------------------------------*" >>$R_FILE
+#    echo "     Test Executed By  : `whoami`" >> $R_FILE
+#    echo "     Date/Time         : `date +%D`/`date +%X`" >> $R_FILE
+#    echo "*-----------------------------------------------------*" >>$R_FILE
+#}
 
 
 #can be called to set txt result file header
-set_results_header_ex(){
-    echo "#testcaseid,testrun,componentid,catagoryid,status,description" >> $R_FILE
-}
+#set_results_header_ex(){
+#    echo "#testcaseid,testrun,componentid,catagoryid,status,description" >> $R_FILE
+#}
 
 
 #can be called to get test category
-component_name(){
-    T_Name=$(get_tname)
-    TestSuite=$(echo $T_Name |cut -d '-' -f1)
-    echo "$TestSuite"
-}
+#component_name(){
+#    T_Name=$(get_tname)
+#    TestSuite=$(echo $T_Name |cut -d '-' -f1)
+#    echo "$TestSuite"
+#}
 
 
 #can be called to log status of a perticular test
@@ -222,123 +223,167 @@ log_status_and_exit_ex(){
 
 
 #can be called to get tsr number
-get_cycle_num()
-{
-    echo "$(date +%m%d%y_%H%M%S)"
-}
+#get_cycle_num()
+#{
+#    echo "$(date +%m%d%y_%H%M%S)"
+#}
 
 
 #can be called to get release;build informations
-get_major_minor_info()
-{
-    MAJOR=$(cat $NS_WDIR/etc/version|head -1|cut -d " " -f2 )
-    MINOR=$(cat $NS_WDIR/etc/version|tail -1|cut -d " " -f2 )
-    echo "${MAJOR}.${MINOR}"
-}
+#get_major_minor_info()
+#{
+#    MAJOR=$(cat $NS_WDIR/etc/version|head -1|cut -d " " -f2 )
+#    MINOR=$(cat $NS_WDIR/etc/version|tail -1|cut -d " " -f2 )
+#    echo "${MAJOR}.${MINOR}"
+#}
 
 
 #can be called to get average transaction response time of a perticular transactions
-get_avg_trans_resp_time(){
-    transName=$1
-    [ -z $transName ] && transName="ALL"
+#get_avg_trans_resp_time(){
+#    transName=$1
+#    [ -z $transName ] && transName="ALL"
 
-    responseTime=$(cat $NS_WDIR/logs/TR${T_RUN_ID}/trans_detail.dat | grep "$transName" | cut -d '|' -f 3| sed 's/ //')
-    echo $responseTime
-}
+#    responseTime=$(cat $NS_WDIR/logs/TR${T_RUN_ID}/trans_detail.dat | grep "$transName" | cut -d '|' -f 3| sed 's/ //')
+#    echo $responseTime
+#}
 
 
 #can be called to apply nsu_server_admin command;or remote command execution 
-remote_exec(){
-    svr="${1}"
-    cmd="${2}"
-    nsu_server_admin -i -s "${svr}" -c "${cmd}" 2>/dev/null| grep -v "Making" | sed '/^$/d'
-    RC=$?
-}
+#remote_exec(){
+#    svr="${1}"
+#    cmd="${2}"
+#    nsu_server_admin -i -s "${svr}" -c "${cmd}" 2>/dev/null| grep -v "Making" | sed '/^$/d'
+#    RC=$?
+#}
 
 
 #can be called to get category wise project or subproject name
-project_name(){
-    testsuitname=$1
-    if [ "X$testsuitname" == "XRegression" ]; then
-         echo "Regression/Regression"
-    fi
-    if [ "X$testsuitname" == "XSmoke" ]; then
-         echo "Smoke/Smoke"
-    fi
-    if [ "X$testsuitname" == "XPerformance" ] || [ "X$testsuitname" == "XPerformance_Cps" ]; then
-         echo "Performance/Performance"
-    fi
-    if [ "X$testsuitname" == "XPerformance_SSL" ]; then
-         echo "Performance/Performance"
-    fi
-    if [ "X$testsuitname" == "Xfunctional" ]; then
-         echo "Functional/Functional"
-    fi
-}
+#project_name(){
+#    testsuitname=$1
+#    if [ "X$testsuitname" == "XRegression" ]; then
+#         echo "Regression/Regression"
+#    fi
+#    if [ "X$testsuitname" == "XSmoke" ]; then
+#         echo "Smoke/Smoke"
+#    fi
+#    if [ "X$testsuitname" == "XPerformance" ] || [ "X$testsuitname" == "XPerformance_Cps" ]; then
+#         echo "Performance/Performance"
+#    fi
+#    if [ "X$testsuitname" == "XPerformance_SSL" ]; then
+#         echo "Performance/Performance"
+#    fi
+#    if [ "X$testsuitname" == "Xfunctional" ]; then
+#         echo "Functional/Functional"
+#    fi
+#}
 
 
 #this is a python utility;can be called to remote login
-remote_ssh(){
-    host="$1"
-    cmd="$2"
+#remote_ssh(){
+#    host="$1"
+#    cmd="$2"
 
-    default_user="root"
-    default_passwd="abeona" 
-
-    user=${default_user}
-    passwd=${default_passwd}
+#    default_user="root"
+#    default_passwd="abeona" 
+#
+#    user=${default_user}
+#    passwd=${default_passwd}
 
     #Safety Checks, If user and password is provided override them
-    [ ! -z $3 ] && user="$3"
-    [ ! -z $4 ] && passwd="$4"
+#    [ ! -z $3 ] && user="$3"
+#    [ ! -z $4 ] && passwd="$4"
+#
+#    PYTHON_SSH="python /home/regression/bin/ssh.py"
 
-    PYTHON_SSH="python /home/regression/bin/ssh.py"
+#    ${PYTHON_SSH} ${host} ${user} ${passwd} "${cmd}"
+#}
 
-    ${PYTHON_SSH} ${host} ${user} ${passwd} "${cmd}"
-}
+#function baslineTR()
+#{
+#    tsrId=$1
+#    tsrNo=$2
+#    testcaseName=$3
+#    tName=$(get_tname)
+#    baselineTr=$(grep -w "$tName" $NS_WDIR/logs/tsr/$tsrId/$tsrNo/${testcaseName}_results.csv|cut -d ',' -f2)
+#    echo $baselineTr
+#}
 
-function baslineTR()
-{
-    tsrId=$1
-    tsrNo=$2
-    testcaseName=$3
-    tName=$(get_tname)
-    baselineTr=$(grep -w "$tName" $NS_WDIR/logs/tsr/$tsrId/$tsrNo/${testcaseName}_results.csv|cut -d ',' -f2)
-    echo $baselineTr
-}
+#fetches data from summary_gdf.data file for baseline/current test run
 
 function testStats()
 {
-    baselineTR=$1
-    testLog=$2 #either it is baseline(0) or current(1)
-    paramName=$3
- 
-    if [ $testLog -eq 0 ]; then
+    test_run=$1
+    test_log=$2 #either it is baseline(0) or current(1)
+    param_string=$3
+    param_name=$4
+    
+    #fetches data for baseline test run (test_log = 0 represents baseline test run)
+    if [ $test_log -eq 0 ]; then
+        param_value="${param_name}_baseline"
+        param_value=`grep -w "${param_string}" $NS_WDIR/logs/TR$test_run/summary_gdf.data |cut -d '|' -f6`
+       # param_value=$(grep -w "$param_string" $NS_WDIR/logs/TR$test_run/summary_gdf.data |cut -d '|' -f6)
+        echo ${param_value}
 
+        #fetches data for current test run (test_log = 1 represents current test run)
+    elif [ $test_log -eq 1 ]; then
+        param_value="${param_name}_current"
+        param_value=$(grep -w "$param_string" $NS_WDIR/logs/TR$test_run/summary_gdf.data |cut -d '|' -f6)
+        echo $param_value
 
-
-        #Need to fetch data for baseline 
-    elif [ $testLog -eq 1 ]; then
-         
-        #Need to fetch data for current test run 
     else
         echo "invalid testLog argument"
     fi
 }
 
-function calculatePercentageChange()
+#Calculates percentage change in baseline and current testrun value for any metric
+function calculate_metric_deviation()
 {
-#will do calculation from baseline and current data file and then dump in another file or we can do one by one by returning value 
+    baseline_test_run=$1
+    current_test_run=$2
+    param_string=$3
+    param_name=$4
+    test_case_name=$5
 
+    #parameter values for baseline and current test run when all parameters are to be matched(param_string =ALL)
+    if [ "XX$3" == "XXALL" ]; then
+        cat $ParamListFile| while read line
+    do
+        baseline_param=$(testStats $baseline_test_run 0 "${line}" "$param_name")
+        current_param=$(testStats $current_test_run 1 "${line}" "$param_name")
+        param_change="${line}_change"
+        param_change=$(echo "$baseline_param" "$current_param" | awk '{print ($1-$2)/$1*100}')
+        param_change=$(echo $param_change | awk '{printf "%.0f\n", $1}')
+        echo "Change in value ${param_change}"
+        get_test_status $param_change "$line" "$test_case_name"
+    done
 
+    #parameter values for baseline and current test run when a given parameter is under evaluation(single param_string)
+    else
+        
+        baseline_param=$(testStats $baseline_test_run 0 "${param_string}" "$param_name")
+        current_param=$(testStats $current_test_run 1 "${param_string}" "$param_name")
+        param_change="${param_name}_change"
+        param_change=`echo ${baseline_param} ${current_param}|awk '{print ($1-$2)/$1*100}'`
+        param_change=$(echo $param_change | awk '{printf "%.0f\n", $1}')
+        echo "Change in value:${param_change}"
+        get_test_status $param_change $param_string "$test_case_name"
+    fi
 }
 
-
-function result()
-{
-
-
-
+function get_test_status() {
+    diff=$1
+    param_name=$2
+    test_case=$3
+    if [ $diff -gt 5 ]; then
+        echo "Value inside failure loop is=$param_name"
+        if [ "${param_name}" == "Active Vusers(NA)" ]; then
+            echo "PASS Regression testcase for ${test_case} test Passed"
+            continue;
+        else
+            echo "FAIL Reression test for ${test_case} failed;because difference of  baseline and current test metric ${param_name} = ${diff} is more than expected difference 5%"
+        fi
+    else
+        echo "PASS Regression testcase for ${test_case} test Passed"
+    fi
 }
-
 
diff --git a/smoke/testcases/SmokeTest_API/check_status b/smoke/testcases/SmokeTest_API/check_status
--- a/smoke/testcases/SmokeTest_API/check_status
+++ b/smoke/testcases/SmokeTest_API/check_status
@@ -9,6 +9,17 @@ TESTRUN_ID=$(get_testidx)
 #This variable holds the path where the save_data() api writes in case of absolue path is used.
 SAVED_FILE_WITH_PATH=$(echo $VAR_VALUE_SUM_RESULT |cut -d "," -f8|sed 's/"//g')  
 
+################################################
+get_status_from_hpd_url_resp_msg_report() 
+{
+  wget "http://10.10.30.38/hpd_url.html" -O "$NS_WDIR/logs/TR${TESTRUN_ID}/hpd_resp.html"
+  TEST_RUN_PATH=$NS_WDIR/logs/TR${TESTRUN_ID} 
+  echo >> $TEST_RUN_PATH/hpd_resp.html
+  diff $TEST_RUN_PATH/hpd_resp.html $TEST_RUN_PATH/api_resp.html
+  rc=$?
+  return $rc
+}
+
 #################################################
 get_status_from_test_report() 
 {
@@ -231,6 +242,19 @@ function check_and_set_status()
   if [ "XX$T_NAME" == "XXXXSMOKE-001-023" ];then 
      get_status_for_cookie_api url_req_0_0_0_2_0_0_0_3_0
   fi  
+
+#Cases for hpd_url_resp_msg
+  if [ "XX$T_NAME" == "XXSMOKE-001-024" ];then
+     get_status_from_hpd_url_resp_msg_report
+     rc=$?
+     if [ $rc -gt 0 ]; then
+         log_status_and_exit_ex "FAIL" "Failed for ns_get_url_resp_msg; Diff returned $rc"
+     else
+         log_status_and_exit_ex "PASS" "Passed for ns_get_url_resp_msg"
+     fi 
+     #passing static name. Unable to get it on run time
+  fi
+ 
   debug_log "End method - check_and_set_status()"  
 }
 
